### ISSUE TITLE
Prepare doc TOC

### ISSUE THREAD

**Issue by palucki** [Qbicz/real-time-shape-detection#12]
- ask about: power supply type

**Comment by Qbicz** [comment]
TODO and bibliography list
https://docs.google.com/document/d/1UqdYqJWDG1qs3GnblMNs6UJYiELM3sqDKRSJ19N6940/edit

**Comment by palucki** [comment]
So having the TOC more or less done, now we want to use resources from google doc and put them in our article as a bibliography list. Please correct me if I am wrong.

**Comment by Qbicz** [comment]
You are right, we want to cite them and probably more if we find something interesting.

**Comment by palucki** [comment]
Ok, so I am adding them now to the bibliography list
