### ISSUE TITLE
Tune Canny threshold BEFORE TUNING SVM

### ISSUE THREAD

**Issue by Qbicz** [Qbicz/real-time-shape-detection#15]
@Qbicz could you please add some additional info?

**Comment by palucki** [comment]
Instead of tuning the threshold I will use fixed value 150 and try to perform convex hull to obtain closed contours

**Comment by Qbicz** [comment]
Good job, thank you! How many objects can we get from the images with the new algorithm?

**Comment by palucki** [comment]
I think it recognizes shape correctly in 90% of cases, when initial contour was not closed (and therefore will not be recognized).
I encourage you to run `hu_moments_gahter.cpp` when you find a spare moment.

**Comment by palucki** [comment]
After reopening:
changed sobel kernel size to 5 for better edges detection and adjusted thresholds.
Also added some useful comand line options.
Acorns not detectable will be fixed when the photo area willl be covered.
