### ISSUE TITLE
Consider using command line parser

### ISSUE THREAD

**Issue by palucki** [Qbicz/real-time-shape-detection#17]
To correctly parse parameters and avoid code explosion we can use some command line parser like boost program options.
I would give a try to minmal yet powerful tool called Clara:
https://github.com/catchorg/Clara

What do you think?

**Comment by Qbicz** [comment]
I also thought about this. Clara 1.0 looks fine, but what do you think about using argparse? https://github.com/hbristow/argparse

The Python argparse is so widespread they using this looks very natural to me. Using it is less verbose than Clara.

**Comment by palucki** [comment]
Seems OK! I'm happy  to learn new framework ;)

**Comment by palucki** [comment]
Ha!
Look what I've found.
OpenCV has its own parser:
https://docs.opencv.org/master/d0/d2e/classcv_1_1CommandLineParser.html

**Comment by Qbicz** [comment]
Nice! I will be happy to try it.

**Comment by palucki** [comment]
As for now we have CommandLineParser from OpenCV included in several modules. Closing issue.
