### ISSUE TITLE
Add json to project includes

### ISSUE THREAD

**Issue by palucki** [Qbicz/real-time-shape-detection#5]
It can be used as subrepo / submodule or downloaded directly to project.

**Comment by palucki** [comment]
It can be done as git subrepo / submodule (then we get latest updates) or simple file save in out project

**Comment by Qbicz** [comment]
Do you mean json files with Hu moments?

**Comment by palucki** [comment]
Json.hpp only ;)

**Comment by Qbicz** [comment]
Then I'm for having it as a submodule ;)

**Comment by Qbicz** [comment]
https://github.com/nlohmann/json

**Comment by palucki** [comment]
Submodule is evil: https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/
Added as a subtree.
Added with command:
git subtree add --prefix PC/svm/json  https://github.com/nlohmann/json.git master --squash
It requires a lot of unnecessary code (tests, doc etc.)
Finally decided to add only raw file in "includes" dir

**Comment by palucki** [comment]
Submodule is evil: https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/
Added as a subtree.
Added with command:
git subtree add --prefix PC/svm/json https://github.com/nlohmann/json.git master --squash
It requires a lot of unnecessary code (tests, doc etc.)
Finally decided to add only raw file in "includes" dir

**Comment by Qbicz** [comment]
Yeah, I've seen some issues with submodules recently ;) If there is too much overhead, raw file is OK. Thanks!

So in this workflow what we will need to do is to pull the updated version of the library file manually when the new release arrives.
